/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.userinterface.sba;

import app.data.Session;
import app.entities.user.StateBarAssoAdmin;
import app.userinterface.BasePanel;
import app.userinterface.BasePanel;
import app.userinterface.admin.CourtPanel;
import com.db4o.User;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import app.data.directories.Directory;
import app.data.org.StateBarAssociation;
import app.entities.user.Lawyer;
import app.entities.user.UserAccount;
import app.entities.workqueues.LawyerApprovalRequest;
import app.entities.workqueues.StateBarAssoWorkQueue;
import app.entities.workqueues.WorkItem;
import javax.swing.JOptionPane;
import app.userinterface.sba.ViewSBARequestsPanel;

/**
 *
 * @author Akshay Relekar
 */
public class StateBarAssociationPanel extends javax.swing.JPanel {

   Directory<String , Lawyer> lawyerDir;
   CardLayout layout;
   StateBarAssoAdmin sba;
    
    public StateBarAssociationPanel() {
        initComponents();
        sba = (StateBarAssoAdmin) Session.getUserAccount().getUser();
//        containerpanel.add(new ViewSBARequestsPanel(),ViewSBARequestsPanel.class.getName());
        layout = (CardLayout) containerpanel.getLayout();
        mainscreenbtn.setEnabled(false);
        welcomelabel.setText("Welcome to the State Bar Association");
        usernamelabel.setText(Session.getUserAccount().getUsername());
        populateTable();
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodypanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        menupanel = new javax.swing.JPanel();
        viewrequestbtn = new javax.swing.JButton();
        mainscreenbtn = new javax.swing.JButton();
        containerpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RequestTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        welcomelabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        usernamelabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1108, 714));
        setPreferredSize(new java.awt.Dimension(1108, 714));

        jSplitPane2.setDividerLocation(250);
        jSplitPane2.setMinimumSize(new java.awt.Dimension(7, 3));
        jSplitPane2.setPreferredSize(new java.awt.Dimension(256, 712));

        viewrequestbtn.setText("View Request");
        viewrequestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrequestbtnActionPerformed(evt);
            }
        });

        mainscreenbtn.setText("Main Screen");
        mainscreenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainscreenbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewrequestbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainscreenbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menupanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(viewrequestbtn)
                .addGap(65, 65, 65)
                .addComponent(mainscreenbtn)
                .addGap(500, 500, 500))
        );

        jSplitPane2.setTopComponent(menupanel);

        containerpanel.setRequestFocusEnabled(false);
        containerpanel.setLayout(new java.awt.CardLayout());

        RequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ApprovalRequest", "From Lawyer", "Date", "Decision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RequestTable);

        containerpanel.add(jScrollPane1, "card2");

        jSplitPane2.setRightComponent(containerpanel);

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        welcomelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        welcomelabel.setForeground(new java.awt.Color(204, 204, 204));
        welcomelabel.setText("WELCOME TO THE STATE BAR ASSOCIATION");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        usernamelabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        usernamelabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomelabel)
                    .addComponent(logoutButton)
                    .addComponent(usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(bodypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

        public void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) RequestTable.getModel();
        model.setRowCount(0);
        for(WorkItem i: ((StateBarAssoWorkQueue) sba.getParent().getWorkQueue()).getWorkList()){
            LawyerApprovalRequest request = (LawyerApprovalRequest) i;
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getLawyer().getFirstName();
            row[2] = request.getRequestDate();
            row[3] = request.getStatus();
            model.addRow(row);
        }
    }
    
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        ((BasePanel)this.getParent()).unloadPage(this);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void viewrequestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrequestbtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= RequestTable.getSelectedRow();
        mainscreenbtn.setEnabled(true);
        if(selectedrow>=0){
            LawyerApprovalRequest req = (LawyerApprovalRequest) RequestTable.getValueAt(RequestTable.getSelectedRow(),0);
            containerpanel.add(new ViewSBARequestsPanel(req,(StateBarAssociation)sba.getParent()),ViewSBARequestsPanel.class.getName());
            layout.show(containerpanel,ViewSBARequestsPanel.class.getName());
        }
        else
        {
           JOptionPane.showMessageDialog(null, "Please select a Record first!!");
           mainscreenbtn.setEnabled(false);
        }
    }//GEN-LAST:event_viewrequestbtnActionPerformed

    private void mainscreenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainscreenbtnActionPerformed
        // TODO add your handling code here:
        containerpanel.remove(this);
        CardLayout layout = (CardLayout) containerpanel.getLayout();
        layout.previous(containerpanel);
        populateTable();
        mainscreenbtn.setEnabled(false);
    }//GEN-LAST:event_mainscreenbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RequestTable;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JPanel containerpanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton mainscreenbtn;
    private javax.swing.JPanel menupanel;
    private javax.swing.JLabel usernamelabel;
    private javax.swing.JButton viewrequestbtn;
    private javax.swing.JLabel welcomelabel;
    // End of variables declaration//GEN-END:variables
}
