/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.userinterface.admin;

import app.business.LoginAction;
import app.data.Network;
import app.data.Session;
import app.entities.user.Admin;
import app.userinterface.BasePanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author Ninad Subhedar (NUID : 001472377)
 */
public class AdminPanel extends javax.swing.JPanel {

    private Admin admin;
    CardLayout layout;
    LoginAction loginAction = new LoginAction();
    Network network = Network.getInstance();
    /**
     * Creates new form LegalEntityPanel
     */
    public AdminPanel() {
        initComponents();
        welcomepanel.setBackground(Color.decode("#9fa8da"));
        menuPanel.setBackground(Color.decode("#b4ffff"));
        admin = (Admin)Session.getUserAccount().getUser();
        welcomelabel.setText("Welcome ");
        usernamelabel.setText(Session.getUserAccount().getUsername());
        this.setPreferredSize(new Dimension(1023, 767));
        containerPanel.add(new StateBarAssociationPanel(network.getSTATE_BAR_ASSOCIATIONS(),network.getUSER_ACCOUNTS()),StateBarAssociationPanel.class.getName());
        containerPanel.add(new CourtPanel(network.getCOURT(),network.getUSER_ACCOUNTS()),CourtPanel.class.getName());
        containerPanel.add(new PublicDomainPanel(network.getPUBLIC_DOMAIN()),PublicDomainPanel.class.getName());    
     
        layout = (CardLayout) containerPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomepanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        welcomelabel = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        menuPanel = new javax.swing.JPanel();
        mainMenu = new javax.swing.JPanel();
        stateBarAssoBtn = new javax.swing.JButton();
        publicDomainBtn = new javax.swing.JButton();
        courtbtn = new javax.swing.JButton();
        containerPanel = new javax.swing.JPanel();

        setOpaque(false);

        welcomepanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        welcomepanel.setOpaque(false);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        welcomelabel.setText("Welcome");

        usernamelabel.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N

        javax.swing.GroupLayout welcomepanelLayout = new javax.swing.GroupLayout(welcomepanel);
        welcomepanel.setLayout(welcomepanelLayout);
        welcomepanelLayout.setHorizontalGroup(
            welcomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomelabel)
                .addGap(7, 7, 7)
                .addComponent(usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(491, 491, 491)
                .addComponent(logoutBtn)
                .addContainerGap())
        );
        welcomepanelLayout.setVerticalGroup(
            welcomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(welcomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn)
                    .addComponent(welcomelabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setOpaque(false);

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setOpaque(false);

        menuPanel.setOpaque(false);

        mainMenu.setOpaque(false);
        mainMenu.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        stateBarAssoBtn.setText("State Bar Associations");
        stateBarAssoBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        stateBarAssoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateBarAssoBtnActionPerformed(evt);
            }
        });
        mainMenu.add(stateBarAssoBtn);

        publicDomainBtn.setText("Public Domains");
        publicDomainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicDomainBtnActionPerformed(evt);
            }
        });
        mainMenu.add(publicDomainBtn);

        courtbtn.setText("Court");
        courtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courtbtnActionPerformed(evt);
            }
        });
        mainMenu.add(courtbtn);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 419, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(menuPanel);

        containerPanel.setOpaque(false);
        containerPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(containerPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        loginAction.logout();
        ((BasePanel)this.getParent()).unloadPage(this);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void stateBarAssoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateBarAssoBtnActionPerformed
        layout.show(containerPanel, StateBarAssociationPanel.class.getName());
    }//GEN-LAST:event_stateBarAssoBtnActionPerformed

    private void publicDomainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicDomainBtnActionPerformed
        layout.show(containerPanel,PublicDomainPanel.class.getName());
    }//GEN-LAST:event_publicDomainBtnActionPerformed

    private void courtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courtbtnActionPerformed
        // TODO add your handling code here:
        layout.show(containerPanel,CourtPanel.class.getName());
    }//GEN-LAST:event_courtbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPanel;
    private javax.swing.JButton courtbtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton publicDomainBtn;
    private javax.swing.JButton stateBarAssoBtn;
    private javax.swing.JLabel usernamelabel;
    private javax.swing.JLabel welcomelabel;
    private javax.swing.JPanel welcomepanel;
    // End of variables declaration//GEN-END:variables
}
